try to do a error 4

diff --git a/github/workflows/ci-cd.yml b/github/workflows/ci-cd.yml
--- a/github/workflows/ci-cd.yml
+++ b/github/workflows/ci-cd.yml
@@ -19,4 +19,6 @@ jobs:
           exit 1
 
       - name: Induce failure
-        run: exit 2
+        run: |
+          echo "This step will fail intentionally"
+          exit 2
