try to do a error 2

diff --git a/github/workflows/ci-cd.yml b/github/workflows/ci-cd.yml
--- a/github/workflows/ci-cd.yml
+++ b/github/workflows/ci-cd.yml
@@ -13,6 +13,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Build Docker image with error
+      - name: Run failing script
         run: |
-          docker build -t your-docker-image-name -f non_existent_dockerfile .
+          echo "This script will fail!"
+          exit 1
